name = "gentechlabs"
compatibility_date = "2024-01-01"
account_id = "a618b777aff85c5360bd847629385b4d"
main = "src/worker.ts"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "https://gentechlabs.net/api/*"
zone_name = "gentechlabs.net"

[[routes]]
pattern = "https://gentechlabs.net/v1/*"
zone_name = "gentechlabs.net"