#!/usr/bin/env python3
"""
Provider Usage Monitor — GenTech Labs
Checks API usage across active providers and logs to vault.
"""

import json
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Vault path
VAULT = Path("/root/vaults/gentech")
LOG_DIR = VAULT / "00-HQ" / "Usage"
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Thresholds (daily)
THRESHOLDS = {
    "xiaomi_mimo": {"daily_tokens": 5_000_000, "daily_cost_usd": 10.0},
    "opencode_go": {"daily_tokens": 5_000_000, "daily_cost_usd": 10.0},
    "nous": {"daily_tokens": 2_000_000, "daily_cost_usd": 5.0},
}

def check_opencode_go():
    """Check OpenCode Go usage via their API."""
    api_key = os.environ.get("OPENCODE_GO_API_KEY", "")
    if not api_key:
        return {"status": "no_key", "message": "OPENCODE_GO_API_KEY not set"}
    
    try:
        import urllib.request
        req = urllib.request.Request(
            "https://opencode.ai/zen/go/v1/auth/key",
            headers={"Authorization": f"Bearer {api_key}", "User-Agent": "curl/8.0"}
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            usage = data.get("data", {}).get("usage", 0)
            limit = data.get("data", {}).get("limit", None)
            return {
                "status": "ok",
                "usage_usd": round(usage, 4),
                "limit_usd": limit,
                "remaining_usd": round(limit - usage, 4) if limit else None,
            }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def check_xiaomi_mimo():
    """Check Xiaomi MiMo token plan usage."""
    # Xiaomi's API may not have a public usage endpoint
    # Log what we know from config
    api_key = os.environ.get("XIAOMI_MIMO_API_KEY", "tp-s7yfatimk7astrb11sqrkxcqvlsd3vhdtalj0xavfnoinixm")
    base_url = "https://token-plan-sgp.xiaomimimo.com/v1"
    
    try:
        import urllib.request
        # Try the /usage endpoint if it exists
        req = urllib.request.Request(
            f"{base_url}/usage",
            headers={"Authorization": f"Bearer {api_key}"}
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return {"status": "ok", "data": data}
    except urllib.error.HTTPError as e:
        # If endpoint doesn't exist, log what we can
        return {
            "status": "endpoint_unavailable",
            "message": f"HTTP {e.code} — usage API may not be public",
            "note": "Check https://token-plan-sgp.xiaomimimo.com dashboard manually"
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def check_nous():
    """Check Nous Research usage."""
    # Nous uses OAuth, may not have a simple usage API
    return {
        "status": "manual",
        "message": "Nous Research — check https://nousresearch.com dashboard",
        "note": "Being dropped — monitor until subscription cancelled"
    }

def generate_report(results):
    """Generate a usage report."""
    now = datetime.utcnow()
    date_str = now.strftime("%Y-%m-%d")
    
    report = f"""# Provider Usage Report — {date_str}
**Generated:** {now.strftime("%Y-%m-%d %H:%M UTC")}

## Active Providers

"""
    alerts = []
    
    for provider, result in results.items():
        status = result.get("status", "unknown")
        emoji = "✅" if status == "ok" else "⚠️" if status in ["endpoint_unavailable", "manual"] else "❌"
        
        report += f"### {emoji} {provider.replace('_', ' ').title()}\n"
        report += f"- **Status:** {status}\n"
        
        if status == "ok":
            if "usage_usd" in result:
                report += f"- **Usage:** ${result['usage_usd']:.4f}\n"
            if "limit_usd" in result and result["limit_usd"]:
                report += f"- **Limit:** ${result['limit_usd']:.2f}\n"
                if result.get("remaining_usd") is not None:
                    remaining = result["remaining_usd"]
                    report += f"- **Remaining:** ${remaining:.4f}\n"
                    if remaining < 2.0:
                        alerts.append(f"🚨 {provider}: ${remaining:.2f} remaining!")
        
        if "message" in result:
            report += f"- **Note:** {result['message']}\n"
        if "note" in result:
            report += f"- **Action:** {result['note']}\n"
        
        report += "\n"
    
    if alerts:
        report += "## 🚨 ALERTS\n\n"
        for alert in alerts:
            report += f"- {alert}\n"
        report += "\n"
    
    report += """## Thresholds (Daily)
| Provider | Token Limit | Cost Limit |
|----------|------------|------------|
| Xiaomi MiMo | 5M tokens | $10.00 |
| OpenCode Go | 5M tokens | $10.00 |
| Nous Research | 2M tokens | $5.00 |

---
*Auto-generated by Provider Usage Monitor*
"""
    
    return report, alerts

def main():
    """Run all provider checks and generate report."""
    print("🔍 Checking provider usage...\n")
    
    results = {
        "xiaomi_mimo": check_xiaomi_mimo(),
        "opencode_go": check_opencode_go(),
        "nous": check_nous(),
    }
    
    report, alerts = generate_report(results)
    
    # Save to vault
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    report_path = LOG_DIR / f"{date_str}-usage-report.md"
    report_path.write_text(report)
    print(f"📄 Report saved: {report_path}")
    
    # Print summary
    print("\n" + report)
    
    # Return alerts for cron
    if alerts:
        print("\n🚨 ALERTS:")
        for alert in alerts:
            print(f"  {alert}")
        return 1  # Non-zero = has alerts
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
