#!/usr/bin/env bash
# GitHub Auth & Repository Configuration Audit
# Usage: Run from any context to diagnose GitHub/Git setup before making changes
# Save output and use it to decide which auth path to take

set -euo pipefail

echo "============================================"
echo "  GitHub Auth & Repo Configuration Audit"
echo "  Generated by: github-auth skill"
echo "============================================"

# 0.1 SSH Key Inventory
echo -e "\n🔐 SSH KEYS"
echo "---"
SSH_DIR="${HOME}/.ssh"
if [ -d "$SSH_DIR" ]; then
  echo "SSH directory: $SSH_DIR"
  keys=$(find "$SSH_DIR" -maxdepth 1 -name "id_*" -not -name "*.pub" 2>/dev/null | sort)
  if [ -n "$keys" ]; then
    echo "Private keys found:"
    while IFS= read -r key; do
      keytype=$(ssh-keygen -l -f "$key" 2>/dev/null | awk '{print $NF}' || echo "unknown")
      echo "  • $(basename "$key") [$keytype]"
    done <<< "$keys"
  else
    echo "❌ No SSH private keys found in $SSH_DIR"
  fi

  pubkeys=$(find "$SSH_DIR" -maxdepth 1 -name "*.pub" 2>/dev/null | wc -l)
  echo "Public keys: $pubkeys"
else
  echo "❌ SSH directory does not exist: $SSH_DIR"
fi

# SSH agent check
if command -v ssh-add &>/dev/null; then
  agent_keys=$(ssh-add -L 2>/dev/null || true)
  if [ -n "$agent_keys" ]; then
    echo "SSH agent has $(echo "$agent_keys" | wc -l) key(s) loaded"
  else
    echo "⚠️  SSH agent not running or no keys loaded"
  fi
fi

# 0.2 Git Remote Audit (Gentech repos)
echo -e "\n📦 GIT REMOTE AUDIT"
echo "---"
REPOS=(
  "/root/vaults/gentech"
  "/root/vaults/gentech/02-Labs/tech-payment-router"
  "/root/vaults/gentech/03-Projects/BirdeyeBIP"
  "/root/vaults/gentech/03-Projects/hermes-kanban"
)

declare -A REMOTE_STATS
for repo in "${REPOS[@]}"; do
  if [ -d "$repo/.git" ]; then
    name=$(basename "$repo")
    url=$(git -C "$repo" config --get remote.origin.url 2>/dev/null || echo "NO_REMOTE")
    branch=$(git -C "$repo" branch --show-current 2>/dev/null || echo "detached")
    status=$(git -C "$repo" status --short 2>/dev/null | wc -l)

    if [[ $url == git@* ]]; then
      auth="SSH"
    elif [[ $url == https://* ]]; then
      auth="HTTPS"
    else
      auth="OTHER"
    fi

    echo "  [$name] ($branch)"
    echo "    Remote: $url"
    echo "    Auth:   $auth"
    echo "    Changes: $status"

    REMOTE_STATS[$auth]=$(( ${REMOTE_STATS[$auth]:-0} + 1 ))
  fi
done

echo -e "\nRemote distribution:"
for auth in SSH HTTPS OTHER NO_REMOTE; do
  count=${REMOTE_STATS[$auth]:-0}
  if [ "$count" -gt 0 ]; then
    echo "  $auth: $count repo(s)"
  fi
done

# 0.3 SSH Access Test
echo -e "\n🔓 SSH ACCESS TEST"
echo "---"
if [ -d "/root/vaults/gentech/.git" ]; then
  echo "Testing: git@github.com:ProtoJay4789/agent-escrow.git"
  if git -C /root/vaults/gentech ls-remote --heads origin &>/dev/null; then
    echo "✅ SSH access: SUCCESS"
  else
    echo "❌ SSH access: FAILED (no valid keys or not added to GitHub)"
  fi
else
  echo " gentech repo not found"
fi

# 0.4 gh CLI Status
echo -e "\n🛠️  GH CLI"
echo "---"
if command -v gh &>/dev/null; then
  echo "gh CLI: $(gh --version | head -1)"
  if gh auth status &>/dev/null; then
    echo "✅ gh authenticated:"
    gh auth status | head -5
  else
    echo "❌ gh installed but NOT authenticated"
  fi
else
  echo "❌ gh CLI not installed"
fi

# 0.5 Token Availability
echo -e "\n🔑 TOKEN AVAILABILITY"
echo "---"
VAULT_ENV="/root/vaults/gentech/.env"
token_found=0

if [ -n "${GITHUB_TOKEN:-}" ] || [ -n "${GITHUB_PAT:-}" ]; then
  echo "✓ Token found in shell environment"
  token_found=1
elif [ -f "$VAULT_ENV" ]; then
  if grep -qE '^GITHUB_(TOKEN|PAT)=' "$VAULT_ENV"; then
    echo "⚠️  Token found in vault .env but NOT loaded into shell"
    echo "   Location: $VAULT_ENV"
    echo "   To load: source $VAULT_ENV (or export the variables manually)"
    token_found=1
  else
    echo "❌ No GITHUB_TOKEN or GITHUB_PAT in $VAULT_ENV"
  fi
else
  echo "❌ Vault .env not found at $VAULT_ENV"
fi

# 0.6 Git Identity
echo -e "\n👤 GIT IDENTITY"
echo "---"
name=$(git config --global user.name 2>/dev/null || echo "not set")
email=$(git config --global user.email 2>/dev/null || echo "not set")
echo "Global user.name: $name"
echo "Global user.email: $email"

# 0.7 Repository Status Summary
echo -e "\n📊 REPOSITORY STATUS SUMMARY"
echo "---"
needs_remote=()
needs_push=()
for repo in "${REPOS[@]}"; do
  if [ -d "$repo/.git" ]; then
    name=$(basename "$repo")
    # Check if remote exists
    if ! git -C "$repo" remote get-url origin &>/dev/null; then
      needs_remote+=("$name")
    fi
    # Check for uncommitted work
    if [ "$(git -C "$repo" status --short 2>/dev/null | wc -l)" -gt 0 ]; then
      needs_push+=("$name")
    fi
  fi
done

if [ ${#needs_remote[@]} -gt 0 ]; then
  echo "Repos missing remote: ${needs_remote[*]}"
else
  echo "✓ All repos have remotes configured"
fi

if [ ${#needs_push[@]} -gt 0 ]; then
  echo "Repos with uncommitted changes: ${needs_push[*]}"
else
  echo "✓ No uncommitted changes detected"
fi

# 0.8 Recommendations
echo -e "\n🎯 RECOMMENDATIONS"
echo "---"

if [ ${#REMOTE_STATS[SSH]:-0} -gt 0 ] && [ ! -d "$SSH_DIR" ]; then
  echo "  ⚠️  Some repos use SSH but no SSH keys exist."
  echo "      Actions: (a) Generate SSH keys and add to GitHub, OR (b) Convert SSH repos to HTTPS"
fi

if [ ${#REMOTE_STATS[HTTPS]:-0} -gt 0 ]; then
  if [ "$token_found" -eq 0 ]; then
    echo "  ⚠️  HTTPS repos detected but no token available."
    echo "      Actions: Run 'gh auth login' or set GITHUB_TOKEN"
  else
    echo "  ✓ HTTPS repos can use the available PAT"
  fi
fi

if [ ${#needs_remote[@]} -gt 0 ]; then
  echo "  ⚠️  Repos without remote need origin set via 'git remote add'"
fi

echo ""
echo "============================================"
echo "  Audit complete"
echo "============================================"
