#!/usr/bin/env bash
# feed-monitor.sh — Pull home timeline + mentions, deduplicate, save to vault
# Cost: ~$0.001 per call (new X API pricing)

set -euo pipefail

VAULT_DIR="/root/vaults/gentech/02-Labs/social-layer-poc/feed"
STATE_FILE="$VAULT_DIR/.last_run_ids"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p "$VAULT_DIR"

# --- Pull home timeline ---
echo "[$(date)] Pulling home timeline..."
TIMELINE=$(xurl timeline -n 50 2>/dev/null || echo '{"data":[]}')

# --- Pull mentions ---
echo "[$(date)] Pulling mentions..."
MENTIONS=$(xurl mentions -n 20 2>/dev/null || echo '{"data":[]}')

# --- Save raw data ---
echo "$TIMELINE" > "$VAULT_DIR/timeline_${TIMESTAMP}.json"
echo "$MENTIONS" > "$VAULT_DIR/mentions_${TIMESTAMP}.json"

# --- Extract post IDs for dedup ---
CURRENT_IDS=$(echo "$TIMELINE" "$MENTIONS" | jq -r '.data[]?.id // empty' 2>/dev/null | sort -u)

# --- Diff against last run (find new posts) ---
if [ -f "$STATE_FILE" ]; then
    NEW_POSTS=$(comm -23 <(echo "$CURRENT_IDS") <(sort "$STATE_FILE"))
else
    NEW_POSTS="$CURRENT_IDS"
fi

NEW_COUNT=$(echo "$NEW_POSTS" | grep -c . || echo "0")

# --- Save state ---
echo "$CURRENT_IDS" > "$STATE_FILE"

# --- Generate summary ---
cat > "$VAULT_DIR/summary_${TIMESTAMP}.md" << EOF
# Feed Monitor — $(date '+%Y-%m-%d %H:%M')

**New posts since last run:** $NEW_COUNT
**Timeline entries:** $(echo "$TIMELINE" | jq '.data | length' 2>/dev/null || echo 0)
**Mentions:** $(echo "$MENTIONS" | jq '.data | length' 2>/dev/null || echo 0)

## New Post IDs
$(echo "$NEW_POSTS" | head -20 | while read id; do echo "- \`$id\`"; done)

---
*Auto-generated by social-layer-poc/feed-monitor.sh*
EOF

echo "[$(date)] Feed monitor complete. $NEW_COUNT new posts found."
echo "Summary: $VAULT_DIR/summary_${TIMESTAMP}.md"
