#!/usr/bin/env bash
# security-radar.sh — Search X for security keywords, alert on matches
# Monitors: exploits, vulnerabilities, rug pulls, security researchers

set -euo pipefail

VAULT_DIR="/root/vaults/gentech/02-Labs/social-layer-poc/security"
ALERT_FILE="$VAULT_DIR/.alerted_ids"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p "$VAULT_DIR"

# --- Security keywords to monitor ---
KEYWORDS=(
    "smart contract exploit"
    "vulnerability disclosed"
    "rug pull"
    "flash loan attack"
    "reentrancy"
    "private key leak"
    "protocol hack"
    "funds stolen"
)

# --- Security researchers to watch ---
RESEARCHERS=(
    "samczsun"
    "ZachXBT"
    "pcaversaccio"
    "tayvano"
    "SlowMist_Team"
    "PeckShieldAlert"
    "CertiKAlert"
    "0xfoobar"
)

# --- Search for each keyword ---
ALL_HITS=""
for keyword in "${KEYWORDS[@]}"; do
    echo "[$(date)] Searching: $keyword"
    RESULTS=$(xurl search "\"$keyword\"" -n 5 2>/dev/null || echo '{"data":[]}')
    HITS=$(echo "$RESULTS" | jq -r '.data[]? | "\(.id)\t\(.author_id // "unknown")\t\(.text[:120])"' 2>/dev/null || true)
    if [ -n "$HITS" ]; then
        ALL_HITS+="$HITS"$'\n'
    fi
    # Respect rate limits — small delay
    sleep 1
done

# --- Check researcher timelines ---
for researcher in "${RESEARCHERS[@]}"; do
    echo "[$(date)] Checking @$researcher"
    USER_DATA=$(xurl user "$researcher" 2>/dev/null || echo '{}')
    USER_ID=$(echo "$USER_DATA" | jq -r '.data.id // empty' 2>/dev/null || true)
    if [ -n "$USER_ID" ]; then
        # Pull their recent posts via raw API
        POSTS=$(xurl "/2/users/$USER_ID/tweets?max_results=5&tweet.fields=created_at,text" 2>/dev/null || echo '{"data":[]}')
        HITS=$(echo "$POSTS" | jq -r '.data[]? | "\(.id)\t'$researcher'\t\(.text[:120])"' 2>/dev/null || true)
        if [ -n "$HITS" ]; then
            ALL_HITS+="$HITS"$'\n'
        fi
    fi
    sleep 1
done

# --- Deduplicate against alerted IDs ---
if [ -f "$ALERT_FILE" ]; then
    NEW_HITS=$(echo "$ALL_HITS" | awk -F'\t' '{print $1}' | sort -u | comm -23 - <(sort "$ALERT_FILE") || true)
else
    NEW_HITS=$(echo "$ALL_HITS" | awk -F'\t' '{print $1}' | sort -u)
fi

NEW_COUNT=$(echo "$NEW_HITS" | grep -c . || echo "0")

# --- Save alert state ---
echo "$ALL_HITS" | awk -F'\t' '{print $1}' | sort -u >> "$ALERT_FILE"

# --- Save results ---
cat > "$VAULT_DIR/radar_${TIMESTAMP}.md" << EOF
# Security Radar — $(date '+%Y-%m-%d %H:%M')

**New alerts:** $NEW_COUNT

## Keyword Hits
$(echo "$ALL_HITS" | grep -v '^$' | while IFS=$'\t' read id author text; do
    echo "- **$author**: ${text}... [\`$id\`]"
done)

---
*Auto-generated by social-layer-poc/security-radar.sh*
EOF

echo "[$(date)] Security radar complete. $NEW_COUNT new alerts."

# --- Output alert summary for cron notification ---
if [ "$NEW_COUNT" -gt 0 ]; then
    echo "🚨 SECURITY ALERT: $NEW_COUNT new matches found"
    echo "$ALL_HITS" | head -5
fi
