#!/usr/bin/env python3
"""Refresh protocol registry files from on-chain state."""

import argparse
import json
import logging
import sys
from pathlib import Path

from eth_abi import encode as abi_encode, decode as abi_decode
from eth_utils import keccak, to_checksum_address

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "defi_skills" / "data"
REGISTRY_DIR = DATA_DIR / "registry"
PLAYBOOKS_DIR = DATA_DIR / "playbooks"


def raw_eth_call(w3, to, sig, types, values, output_types):
    """Minimal eth_call helper (same as engine/resolvers/common.py)."""
    selector = keccak(sig.encode())[:4]
    calldata = selector + abi_encode(types, values) if types and values else selector
    result = w3.eth.call({"to": to, "data": "0x" + calldata.hex()})
    return abi_decode(output_types, result)


def get_w3():
    """Create web3 instance from env."""
    import os
    from dotenv import load_dotenv
    load_dotenv()
    api_key = os.getenv("ALCHEMY_API_KEY")
    if not api_key:
        logger.error("ALCHEMY_API_KEY not set")
        sys.exit(1)
    from web3 import Web3
    base_url = os.getenv("ALCHEMY_URL", "https://eth-mainnet.g.alchemy.com/v2")
    return Web3(Web3.HTTPProvider(f"{base_url}/{api_key}"))


def get_token_resolver():
    """Create a TokenResolver for symbol lookups."""
    from defi_skills.engine.token_resolver import TokenResolver
    return TokenResolver()


# EigenLayer

def refresh_eigenlayer(w3, token_resolver):
    """Verify whitelisted EigenLayer strategies and update the registry."""
    pb = json.loads((PLAYBOOKS_DIR / "eigenlayer.json").read_text())
    sm_address = pb["contracts"]["strategy_manager"]["address"]
    sm_addr = to_checksum_address(sm_address)
    seed_map = pb.get("strategy_map", {})

    logger.info("Querying EigenLayer StrategyManager...")
    logger.info(f"  Seed strategies from playbook: {len(seed_map)}")

    strategy_map = {}
    valid_tokens = []

    for sym, strat_addr in seed_map.items():
        strat_cs = to_checksum_address(strat_addr)
        try:
            # Verify still whitelisted
            (whitelisted,) = raw_eth_call(
                w3, sm_addr,
                "strategyIsWhitelistedForDeposit(address)", ["address"], [strat_cs], ["bool"]
            )
            if not whitelisted:
                logger.info(f"  {sym} ({strat_cs}) — NOT whitelisted, skipping")
                continue

            # Resolve underlying token to confirm symbol
            (token_addr,) = raw_eth_call(
                w3, strat_cs,
                "underlyingToken()", [], [], ["address"]
            )
            token_cs = to_checksum_address(token_addr)
            info = token_resolver.resolve_by_address(token_cs)
            resolved_sym = info["symbol"] if info and info.get("symbol") else sym
            strategy_map[resolved_sym] = strat_cs
            valid_tokens.append(resolved_sym)
            logger.info(f"  {resolved_sym} -> {strat_cs} (whitelisted)")
        except Exception as e:
            logger.warning(f"  {sym} ({strat_cs}) — query failed: {e}")
            continue

    if not strategy_map:
        logger.error("  No strategies verified — skipping write")
        return None

    registry = {
        "_generated": "auto-generated by refresh_registry.py — do not edit",
        "strategy_map": strategy_map,
        "valid_tokens": sorted(valid_tokens),
    }

    logger.info(f"  Verified {len(strategy_map)}/{len(seed_map)} strategies")
    return registry


# Compound V3

def refresh_compound_v3(w3, token_resolver):
    """Query Compound Comet for supported collateral and base token."""
    pb = json.loads((PLAYBOOKS_DIR / "compound_v3.json").read_text())
    comet_address = pb["contracts"]["comet_usdc"]["address"]
    comet_addr = to_checksum_address(comet_address)

    logger.info("Querying Compound V3 Comet...")

    # Base token (what you borrow)
    (base_token_addr,) = raw_eth_call(w3, comet_addr, "baseToken()", [], [], ["address"])
    base_cs = to_checksum_address(base_token_addr)
    base_info = token_resolver.resolve_by_address(base_cs)
    base_symbol = base_info["symbol"] if base_info else "USDC"
    logger.info(f"  Base token: {base_symbol} ({base_cs})")

    # Collateral assets
    (num_assets,) = raw_eth_call(w3, comet_addr, "numAssets()", [], [], ["uint8"])
    logger.info(f"  Number of collateral assets: {num_assets}")

    collateral_tokens = []
    for i in range(num_assets):
        try:
            # getAssetInfo returns a struct: (offset, asset, priceFeed, scale, borrowCF, liquidateCF, liquidationFactor, supplyCap)
            result = raw_eth_call(
                w3, comet_addr,
                "getAssetInfo(uint8)", ["uint8"], [i],
                ["uint8", "address", "address", "uint256", "uint256", "uint256", "uint256", "uint128"]
            )
            asset_addr = to_checksum_address(result[1])
            info = token_resolver.resolve_by_address(asset_addr)
            if info and info.get("symbol"):
                collateral_tokens.append(info["symbol"])
                logger.info(f"  Collateral[{i}]: {info['symbol']} ({asset_addr})")
        except Exception as e:
            logger.warning(f"  Skipping asset index {i}: {e}")
            continue

    # All tokens that can be supplied = base + collateral
    all_supply_tokens = sorted(set([base_symbol] + collateral_tokens))

    registry = {
        "_generated": "auto-generated by refresh_registry.py — do not edit",
        "base_token": base_symbol,
        "collateral_tokens": sorted(collateral_tokens),
        "supply_tokens": all_supply_tokens,
        "borrow_tokens": [base_symbol],
    }

    logger.info(f"  Found {len(collateral_tokens)} collateral assets")
    return registry


# Main

PROTOCOLS = {
    "eigenlayer": refresh_eigenlayer,
    "compound_v3": refresh_compound_v3,
}


def main():
    parser = argparse.ArgumentParser(description="Refresh protocol registry from on-chain state")
    parser.add_argument("--protocol", choices=list(PROTOCOLS.keys()), help="Refresh only one protocol")
    parser.add_argument("--dry-run", action="store_true", help="Print results without writing files")
    args = parser.parse_args()

    w3 = get_w3()
    token_resolver = get_token_resolver()

    protocols = {args.protocol: PROTOCOLS[args.protocol]} if args.protocol else PROTOCOLS
    REGISTRY_DIR.mkdir(parents=True, exist_ok=True)

    results = {}
    for name, refresh_fn in protocols.items():
        logger.info(f"\n{'='*50}")
        logger.info(f"Refreshing: {name}")
        logger.info(f"{'='*50}")
        try:
            registry = refresh_fn(w3, token_resolver)
            if registry:
                results[name] = registry
                if not args.dry_run:
                    out_path = REGISTRY_DIR / f"{name}.json"
                    out_path.write_text(json.dumps(registry, indent=2) + "\n")
                    logger.info(f"  Written to {out_path}")
                else:
                    logger.info(f"  [dry-run] Would write:")
                    logger.info(json.dumps(registry, indent=2))
        except Exception as e:
            logger.error(f"  Failed: {e}")
            import traceback
            traceback.print_exc()

    logger.info(f"\nDone. Refreshed {len(results)}/{len(protocols)} protocols.")
    return 0 if len(results) == len(protocols) else 1


if __name__ == "__main__":
    sys.exit(main())
